/*
 * Service worker for the Korean study app — generated by scripts/build-sw.mjs.
 * Do not edit by hand; the version below is stamped at build time.
 *
 * Caching strategy, chosen so a new release can never get stuck on the phone:
 *
 *  - Navigations are network-first. If the phone is online it always gets the
 *    current page; the cached copy is only used when the network fails.
 *  - Assets are cache-first, but the cache name carries the app version, so a
 *    new release starts from an empty cache and the old one is deleted.
 *  - The worker takes over immediately (skipWaiting + clients.claim) rather
 *    than waiting for every tab to close, which on a home-screen app could be
 *    never.
 */

const VERSION = '1.4.0'
const CACHE = 'korean-study-v' + VERSION

/* The shell needed to open the app offline. Hashed asset URLs are added as
 * they are requested, so this list does not need to know their names. */
const SHELL = ['./', './index.html', './manifest.webmanifest']

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(SHELL))
      // A missing shell entry must not block installation entirely.
      .catch(() => undefined)
      .then(() => self.skipWaiting())
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key)))
      )
      .then(() => self.clients.claim())
  )
})

self.addEventListener('message', (event) => {
  if (event.data === 'skip-waiting') self.skipWaiting()
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  // Only this app's own files; never intercept anything cross-origin.
  if (url.origin !== self.location.origin) return

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone()
          caches.open(CACHE).then((cache) => cache.put(request, copy))
          return response
        })
        .catch(() =>
          caches.match(request).then((cached) => cached || caches.match('./index.html'))
        )
    )
    return
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone()
          caches.open(CACHE).then((cache) => cache.put(request, copy))
        }
        return response
      })
    })
  )
})
